#+title: TLC SRC---Projects

** a HoTT Programming Language

We would like a practical programming language based on Univalent Foundations---the new foundation of mathematics. Of course, firstly we must understand what that _is_. To this end we are currently walking through [[http://www.cs.cmu.edu/~rwh/courses/hott/][Robert Harper's lectures on Higher Type Theory (aka HoTT)]]. Hopefully it will be possible to integrate ideas of Higher Type Theory into existing programming languages such as [[http://idris-lang.org][Idris]] and [[https://haskell.org][Haskell]]. Failing that, the Triplet programming language will be born.


** Haskell ⇔ Swift

The equivalent of [[https://hackage.haskell.org/package/language-c-inline][language-c-line]] for [[http://swiftlang.eu/][Swift]].

- Write a Swift parser in Haskell, language-swift-quote.
- Build Swift quasiquotation, language-swift-inline.
#+begin_comment
- Manuel Chakravarty is assisting with the direction and code reviewing.
#+end_comment


** Module System for Idris

- in the style in the ML module system.
- inspiration from Agda and Coq module systems.
- Edwin Brady is not opposed and would be happy to receive a proposal.
- Hopefully we can rope Edwin into helping.
- /Call for assistance/: Module Systems' folk, we need some hand-holding.


** Systems Programming with Haskell

- The Go programming language is becoming increasingly popular in the systems/infrastructure/cloud space. We'd like to show that the Glorious GHC is already highly suited to this application. To demonstrate this, we'll do some ports of popular Go project in Haskell. e.g. =etc=.

- Using Turtle and Nix to port Bash scripts to Haskell scripts.


** Nix in Haskell

[[http://nixos.org/nix][Nix]] is a purely functional package system but it's currently written in a combination of C and Perl. Some kind-hearted folks have already started to remedy this situation and we'd like to help. See the [[https://github.com/jwiegley/hnix][hnix project on GitHub]].


** Truffled PureScript

It would be nice to have a principled programming language that was practical to use on the JVM. [[http://purescript.org/][PureScript]] is such a language and [[https://github.com/slamdata/truffled-purescript][Truffled PureScript]] is an endeavour to bring about an implementation of PureScript on the JVM using Graal/Truffle[fn:1]. We'd like to help.


[fn:1] [[http://www.slideshare.net/ThomasWuerthinger/graal-truffle-ethdec2013][Graal and Truffle: One VM to Rule Them All]]
