#+html_head: <meta charset="utf-8"/>
#+html_head: <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
#+html_head: <link rel="stylesheet" href="css/styles.css">
#+html_head: <link rel="stylesheet" href="css/style.css">

#+title: TLC SRC

#+begin_html
<small>
#+end_html
The Systems Research Centre[fn:1] that practises [[https://existentialtype.wordpress.com/2011/03/27/the-holy-trinity/][computational trinitarianism]]:
#+begin_html
</small>
#+end_html

#+begin_html
<div class="tlc">
  <p><span class="tlcx">T</span>ypes, <span class="tlcx">L</span>ogic, &amp; <span class="tlcx">C</span>ategories</p>
</div>
#+end_html

We build software systems that are elegant, reliable, maintainable. We resist
the temptation to compromise our principles in order to pursue high
performance[fn:2].

 # #+begin_html
 # <h2 id="invitation">Contact us</h2>
 # #+end_html

We love to work, learn, and collaborate with entrepreneurs, programmers, researchers, and autodidacts.
#+begin_html
<p class="center">
<a href="mailto:hello@tlcsrc.com">hello@tlcsrc.com</a>
</p>
#+end_html

[fn:1] Named in homage to the original SRC,
[[https://en.wikipedia.org/wiki/DEC_Systems_Research_Center][DEC SRC]].
Unfortunately, not actually a research centre---more of a software
consultancy.
[fn:2] We do like low-level bit-twiddling tricks, it's just that we prefer
to get things right before we make them fast. In the long-term, we believe
that high-level principled design will lead to the leveraging of the an ever
broader range of low-level bit-twiddling in a safe, automated manner for
high performance together with high confidence.
