#!/usr/bin/env bash

set -eu

if [[ ! -r ./gh-pages/.git ]]; then
  echo "gh-pages submodule is not initialized. Do you need to \`git submodule update --init --recursive\`?"
  exit 1
fi

make
cd gh-pages
git add -A
git commit -m "Updated at $(timestamp)"
git push
