#!/usr/bin/env bash

set -eu

if [[ ! -d gh-pages ]]; then
  echo "gh-pages does not exist. Do you need to \`git submodule update --init\`?"
  exit 1
fi

make
cd gh-pages
git add -A
git commit -m "Updated at $(timestamp)"
git push
